project:
  type: website
  output-dir: docs

website:
  title: "Brazos Nexus"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "STDs/STIs"
        menu:
          - text: "Chlamydia"
            href: chlamydia.qmd
          - text: "Gonorrhea"
            href: gonorrhea.qmd
          - text: "HIV"
            href: hiv.qmd
          - text: "Syphilis"
            href: syphilis.qmd
      - text: "Vector Surveillance"
        menu:
          - text: "West Nile Virus"
            href: wnile.qmd
      - text: "About"
        href: about.qmd
format:
  dashboard:
    scrolling: true

