---
title: "About Brazos Nexus"
format: html
theme: styles.css
---
## Data Source

source? ask georgette

### Reporting Periods
This dashboard is maintained once a week on Fridays, when new reported data is entered. 

## Methodology
### Technical Setup
This dashboard was built using R, Quarto, and the following packages: tidyverse, tigris, sf, lubridate, leaflet, plotly, bslib, DT.

Geometry for Zip Code Boudaries is based off shapefile accessible <strong> <a href="https://services1.arcgis.com/x5wCko8UnSi4h0CB/ArcGIS/rest/services/Brazos_County_City_Limits_and_Zip_Codes_WFL1/FeatureServer/3" target="_blank" rel="noopener noreferrer"> here </a> </strong>.

### Confidentiality
Geographic summaries are displayed at the ZIP Code Tabulation Area (ZCTA) level to balance spatial detail with patient confidentiality and facilitate routine dashboard maintenance.

## Dashboard Development

This dashboard was designed and developed by <strong> <a href="https://linkedin.com/in/clemence-fichet-8933b4274" target="_blank" rel="noopener noreferrer"> Clemence A. Fichet </a> </strong>, an MPH student in Epidemiology at the Texas A&M University School of Public Health, during a practicum with the Brazos County Health District. This dashboard was included as a deliverable in the Applied Practice Experience (APEx) program at the School of Public Health.

Questions about development can be fielded to clemence.fichet@tamu.edu.